const languages = {
    en: {
        // --- Global (Navigation & Footer) ---
        "nav-brand-text": "BUST THE CASINO",
        "nav-strategy": "Strategy",
        "nav-tools": "Tools",
        "nav-about": "About Us",
        "footer-copyright": "&copy; 2025 Bust the Casino. All Rights Reserved.",
        "footer-disclaimer": "Please gamble responsibly. This website is for academic and entertainment purposes only.",

        // --- Home Page (index.html) ---
        "hero-title-1": "MASTER THE TABLE",
        "hero-title-2": "BUST THE CASINO",
        "hero-subtitle": "We provide data-driven game strategies, tutorials, and practical tools to make you a smarter player.",
        "hero-button": "Explore Game Strategies",
        "strategy-title": "STRATEGY CENTER",
        "strategy-subtitle": "Start with the most popular games to master the core strategies.",
        "blackjack-title": "Blackjack",
        "blackjack-desc": "Known as the most skill-based game in the casino. Learn basic strategy and card counting to minimize the house edge.",
        "baccarat-title": "Baccarat",
        "baccarat-desc": "A fast-paced and simple game beloved by many players. Understand the math behind Player, Banker, and Tie bets to make the most informed decisions.",
        "uth-title": "Ultimate Texas Hold'em",
        "uth-desc": "Combines the skill of Texas Hold'em with the thrill of casino play. Learn to make optimal raise or fold decisions based on your hole cards and the community cards.",

        // --- Blackjack Page (blackjack.html) ---
        "blackjack-page-title": "Blackjack Section",
        "blackjack-page-subtitle": "Master the strategy to minimize the house edge. We provide a comprehensive guide from beginner to advanced.",
        "blackjack-rules-title": "Rules & How to Play",
        "blackjack-rules-desc": "Start from scratch and learn the basic flow, card values, and various options in Blackjack.",
        "blackjack-basic-title": "Basic Strategy",
        "blackjack-basic-desc": "Learn to make the mathematically optimal decision in any situation. This is the first step to beating Blackjack.",
        "blackjack-advanced-title": "Advanced Strategy",
        "blackjack-advanced-desc": "Explore the world of card counting and learn how to gain a real advantage over the house.",

        // --- Baccarat Page (baccarat.html) ---
        "baccarat-page-title": "Baccarat Section",
        "baccarat-page-subtitle": "Fast-paced and simple rules. Understand the math behind Player, Banker, and Tie to make the best betting decisions.",
        "baccarat-rules-title": "Rules & How to Play",
        "baccarat-rules-desc": "Start from scratch and learn the dealing process, third-card rules, and different betting options.",
        "baccarat-basic-title": "Basic Strategy",
        "baccarat-basic-desc": "Analyze the true odds and house edge of each bet to understand why betting on the Banker is the best mathematical choice.",
        "baccarat-divination-title": "Probability Oracle",
        "baccarat-divination-desc": "A random simulator based on I-Ching trigrams to explore short-term probability fluctuations. For entertainment only.",
        
        // --- UTH Page (uth.html) ---
        "uth-page-title": "Ultimate Texas Hold'em",
        "uth-page-subtitle": "Combines the thrill of traditional Texas Hold'em with the speed of casino table games. Learning when to bet big is the key to beating the dealer.",
        "uth-rules-title": "Rules & How to Play",
        "uth-rules-desc": "Learn the game flow, different betting stages, and the all-important poker hand rankings.",
        "uth-basic-title": "Basic Strategy",
        "uth-basic-desc": "Analyze your starting hands and learn when to make the 4x, 2x, or fold decision before and after the flop.",

        // --- Blackjack Rules Page (blackjack-rules.html) ---
        "back-to-blackjack": "&larr; Back to Blackjack Section",
        "bkr-title": "Rules & How to Play",
        "bkr-obj-title": "Objective of the Game",
        "bkr-obj-desc": "The objective of Blackjack is simple: get a hand total closer to 21 than the dealer, without going over 21. If your first two cards total exactly 21 (an Ace and a 10-value card), you have a \"Blackjack\" and win immediately with a higher payout.",
        "bkr-card-title": "Card Values",
        "bkr-card-1": "<b>Number Cards (2-10):</b> Are worth their face value.",
        "bkr-card-2": "<b>Face Cards (J, Q, K):</b> Are each worth 10 points.",
        "bkr-card-3": "<b>Ace (A):</b> Is the most special card. It can be worth 1 or 11, whichever is more favorable for the hand. For example, (A, 8) is 19. (A, 5, 8) is 14 (the Ace counts as 1 to avoid busting).",
        "bkr-actions-title": "Player's Actions",
        "bkr-hit-title": "Hit:",
        "bkr-hit-desc": "Request another card from the dealer. You can keep hitting until you decide to stand or your total exceeds 21 (bust).",
        "bkr-stand-title": "Stand:",
        "bkr-stand-desc": "You are satisfied with your hand and want to take no more cards. It is then the dealer's turn to act.",
        "bkr-double-title": "Double Down:",
        "bkr-double-desc": "After receiving your first two cards, you can choose to double your initial bet. In return, you receive only one more card and must stand afterward. This is a key strategy to increase profit in favorable situations.",
        "bkr-split-title": "Split:",
        "bkr-split-desc": "If your first two cards are of the same value (e.g., two 8s or two Kings), you can split them into two separate hands. You must place an additional bet equal to your original bet. You then play each hand independently.",
        "bkr-dealer-title": "Dealer's Rules",
        "bkr-dealer-desc": "The dealer has no freedom of choice and must follow strict house rules. Typically, the dealer must hit on a total of 16 or less and must stand on a total of 17 or more (including a soft 17, which is an Ace and a 6).",

        // --- Baccarat Rules Page (baccarat-rules.html) ---
        "back-to-baccarat": "&larr; Back to Baccarat Section",
        "bcr-title": "Rules & How to Play",
        "bcr-obj-title": "Objective of the Game",
        "bcr-obj-desc": "The goal in Baccarat is simpler than Blackjack. You are not playing against the dealer; instead, you are betting on which of two hands, the \"Player\" or the \"Banker\", will have a total closest to 9.",
        "bcr-card-title": "Card Values",
        "bcr-card-1": "<b>Number Cards (2-9):</b> Are worth their face value.",
        "bcr-card-2": "<b>10, J, Q, K:</b> Are each worth 0 points.",
        "bcr-card-3": "<b>Ace (A):</b> Is worth 1 point.",
        "bcr-card-desc": "The total value of a hand is the rightmost digit of the sum of the cards. For example, a hand of 7 and 8 totals 15, so its value is 5. A hand of K and 9 has a value of 9, which is a \"Natural\".",
        "bcr-payouts-title": "Bets and Payouts",
        "bcr-player-title": "Bet on Player:",
        "bcr-player-desc": "If you bet on the Player hand to win, the payout is 1 to 1.",
        "bcr-banker-title": "Bet on Banker:",
        "bcr-banker-desc": "If you bet on the Banker hand to win, the payout is also 1 to 1, but the house takes a 5% commission from the winnings. This is because the Banker bet has a slightly higher mathematical probability of winning.",
        "bcr-tie-title": "Bet on Tie:",
        "bcr-tie-desc": "If you bet that both hands will have the same total, the payout is typically 8 to 1. While the payout is high, this is the worst bet in terms of house edge and is not recommended for long-term play.",
        "bcr-third-title": "The Third Card Rule",
        "bcr-third-desc": "This is the most complicated part of Baccarat, but the good news is you don't need to memorize it; the dealer handles it automatically. The rules dictate when the Player and Banker must draw a third card.",
        "bcr-third-player": "Player's Rule:",
        "bcr-third-p1": "If the Player's first two cards total 0-5, the Player must draw a third card.",
        "bcr-third-p2": "If the total is 6 or 7, the Player must stand.",
        "bcr-third-p3": "If the total is 8 or 9 (a \"Natural\"), both hands stand and the game ends.",
        "bcr-third-banker": "Banker's Rule (depends on the Player's third card):",
        "bcr-third-b-desc": "The Banker's rule is more complex, as summarized in the table below:",
        "bcr-table-b-total": "Banker's First Two-Card Total",
        "bcr-table-p-card": "Player's Third Card",
        "bcr-table-action": "Banker's Action",
        "bcr-table-r1": "is not 8",
        "bcr-table-hit1": "Draw",
        "bcr-table-r2": "is 2, 3, 4, 5, 6, 7",
        "bcr-table-hit2": "Draw",
        "bcr-table-r3": "is 4, 5, 6, 7",
        "bcr-table-hit3": "Draw",
        "bcr-table-r4": "is 6, 7",
        "bcr-table-hit4": "Draw",
        "bcr-table-r5": "7",
        "bcr-table-stand": "Stand",

        // --- Blackjack Basic Strategy Page (blackjack-basic-strategy.html) ---
        "bks-title": "Blackjack Basic Strategy",
        "bks-intro": "Basic strategy is the cornerstone of beating Blackjack. It's based on mathematical probabilities and tells you the optimal decision (Hit, Stand, Double, Split) for any given situation (your hand vs. the dealer's upcard) to maximize your long-term return. Strictly following this chart can reduce the house edge to about 0.5%.",
        "bks-legend-title": "Legend",
        "bks-legend-h": "H = Hit",
        "bks-legend-s": "S = Stand",
        "bks-legend-d": "D = Double",
        "bks-legend-p": "P = Split",
        "bks-legend-sur": "SR = Surrender",
        "bks-hard-title": "Hard Totals",
        "bks-soft-title": "Soft Totals",
        "bks-pairs-title": "Pairs",
        "bks-dealer-card": "Player's Hand",
        "bks-dealer-card-2": "Player's Hand",
        "bks-dealer-card-3": "Player's Hand",

        // --- Baccarat Basic Strategy Page (baccarat-basic-strategy.html) ---
        "bcs-title": "Baccarat Basic Strategy",
        "bcs-intro": "Baccarat strategy is not about in-game decisions, but about pre-bet choices. Unlike Blackjack, once bets are placed, the game plays out according to fixed rules. Therefore, the only strategy is to choose the bet with the lowest house edge.",
        "bcs-analysis-title": "Analysis of the Three Main Bets",
        "bcs-banker-title": "1. Banker Bet - The Best Choice",
        "bcs-banker-desc": "Despite the 5% commission on winnings, the Banker bet is the most mathematically advantageous choice. The drawing rules are slightly in favor of the Banker's hand winning.",
        "bcs-banker-edge-label": "House Edge",
        "bcs-banker-win-label": "Win Rate",
        "bcs-player-title": "2. Player Bet",
        "bcs-player-desc": "The Player bet also has a very low house edge, making it a decent second choice. If you prefer to avoid calculating commissions, it's an acceptable strategy.",
        "bcs-player-edge-label": "House Edge",
        "bcs-player-win-label": "Win Rate",
        "bcs-tie-title": "3. Tie Bet - Avoid at All Costs",
        "bcs-tie-desc": "While the 8-to-1 payout for a Tie is tempting, its probability of occurring is very low, resulting in an extremely high house edge. In the long run, the Tie bet is the fastest way to lose money.",
        "bcs-tie-edge-label": "House Edge",
        "bcs-tie-win-label": "Occurrence",
        "bcs-summary-title": "Conclusion: The One and Only Strategy",
        "bcs-summary-desc": "The optimal strategy for Baccarat is simple: **Always bet on the Banker**. Don't be swayed by 'The Road' or your gut feelings; mathematics proves the Banker bet is the best decision you can make at the table. At the same time, **absolutely avoid the Tie bet**.",
        
        // --- Baccarat Divination Tool (baccarat-divination.html) ---
        "div-title": "Probability Oracle",
        "div-subtitle": "A random number generator based on I-Ching Trigrams",
        "placeholder": "Click the button below to start simulation",
        "btn-start": "Start Simulation",
        "div-disclaimer": "Disclaimer: This tool is for entertainment purposes only. Its results are based on a pseudo-random algorithm and do not represent any real-world prediction or constitute any betting advice. Please always refer to official strategies and gamble responsibly.",
        
        // --- Blackjack Advanced Strategy Page (blackjack-advanced-strategy.html) ---
        "bka-title": "Advanced Strategy: Intro to Card Counting (Hi-Lo System)",
        "bka-intro": "Card counting isn't a superpower memory trick from movies; it's a system to track the ratio of high cards to low cards in the deck. When the remaining deck is rich in high cards (10, J, Q, K, A), the advantage shifts heavily to the player, as the probability of getting a Blackjack increases. Hi-Lo is the most popular and easiest system to learn.",
        "bka-step1-title": "Step 1: Assigning Values",
        "bka-step1-desc": "The Hi-Lo system categorizes all cards into three groups and assigns a simple value. Your goal is not to remember every card, but to maintain a single, ongoing count.",
        "bka-step1-low": "Low Cards (2, 3, 4, 5, 6)",
        "bka-step1-neutral": "Neutral Cards (7, 8, 9)",
        "bka-step1-high": "High Cards (10, J, Q, K, A)",
        "bka-step2-title": "Step 2: Keeping the Running Count",
        "bka-step2-desc": "Starting from a new shoe, the running count is 0. For every card dealt, you mentally add or subtract its value from the count.",
        "bka-step2-example": "<b>Example:</b> The first cards dealt are 10, 3, K, 8, A, 5. Your mental calculation would be:<br>10(-1), 3(+1), K(-1), 8(0), A(-1), 5(+1) → <span class='font-bold text-lg' style='color:var(--color-accent-gold);'>-1 + 1 - 1 + 0 - 1 + 1 = -1</span>.<br>So, after the first round, the running count is <span class='font-bold'>-1</span>. You only need to remember this number and continue counting in the next round.",
        "bka-step2-goal": "A positive running count (e.g., +5) means more small cards have been dealt, leaving the deck rich in high cards, which is advantageous to the player. Conversely, a negative count favors the dealer.",
        "bka-step3-title": "Step 3: Calculating the True Count - The Key",
        "bka-step3-desc": "The running count can be misleading. A running count of +5 means very little with 6 decks remaining, but it's a huge advantage if only 1 deck is left. Therefore, we must standardize the count to get the 'True Count'.",
        "bka-step3-formula": "True Count = Running Count / Decks Remaining",
        "bka-step3-example": "<b>Example:</b> Your running count is +10. It's a 6-deck game, and you estimate about 4 decks are left in the shoe. Your true count is:<br><span class='font-bold text-lg' style='color:var(--color-accent-gold);'>+10 / 4 = +2.5</span>. The true count is what you base your betting decisions on. Estimating remaining decks takes practice.",
        "bka-step4-title": "Step 4: Bet Spreading",
        "bka-step4-desc": "The whole point of counting is to bet big when you have the advantage and small when you don't. You should have a predetermined betting unit and strategy.",
        "bka-table-tc": "True Count",
        "bka-table-bet": "Suggested Bet",
        "bka-table-advantage": "Player Edge",
        "bka-bet1": "1 Unit (Min Bet)",
        "bka-bet2": "2 Units",
        "bka-bet3": "4 Units",
        "bka-bet4": "8 Units",
        "bka-bet5": "10-12 Units",
        "bka-disclaimer-title": "Important Warning",
        "bka-disclaimer-desc": "Card counting is extremely challenging and requires immense practice to maintain accuracy in a distracting casino environment. Furthermore, casinos actively look for and ban card counters. This tutorial is for academic purposes only. Do not attempt without understanding the risks.",
        
        // --- UTH Rules Page (uth-rules.html) ---
        "back-to-uth": "&larr; Back to UTH Section",
        "uthr-title": "UTH Rules & How to Play",
        "uthr-obj-title": "Objective of the Game",
        "uthr-obj-desc": "The objective of Ultimate Texas Hold'em is to form the best five-card poker hand using your two hole cards and five community cards to beat the dealer. Unlike traditional poker, you are playing against the house, not other players.",
        "uthr-hands-title": "Poker Hand Rankings",
        "uthr-hands-desc": "The hand rankings are identical to traditional Texas Hold'em, listed from highest to lowest:",
        "uthr-table-rank": "Rank",
        "uthr-table-hand": "Hand",
        "uthr-table-example": "Example",
        "uthr-rank-1": "Royal Flush",
        "uthr-rank-2": "Straight Flush",
        "uthr-rank-3": "Four of a Kind",
        "uthr-rank-4": "Full House",
        "uthr-rank-5": "Flush",
        "uthr-rank-6": "Straight",
        "uthr-rank-7": "Three of a Kind",
        "uthr-rank-8": "Two Pair",
        "uthr-rank-9": "One Pair",
        "uthr-rank-10": "High Card",
        "uthr-flow-title": "Game Flow & Betting",
        "uthr-flow-1-title": "1. Initial Bets (Ante & Blind)",
        "uthr-flow-1-desc": "Before the game starts, you must make two equal bets: the 'Blind' and the 'Ante'. For example, if you bet $10 on the Blind, you must also bet $10 on the Ante. You may also make an optional 'Trips' bonus bet.",
        "uthr-flow-2-title": "2. The Deal & First Bet (Pre-Flop)",
        "uthr-flow-2-desc": "You and the dealer each receive two hole cards (face down). After looking at your cards, you have two choices:<br>• <b>Check:</b> Do nothing and wait to see the community cards.<br>• <b>Play Bet:</b> Make a bet of 3x or 4x your Ante bet in the 'Play' spot. Once you bet, you cannot bet again in the hand.",
        "uthr-flow-3-title": "3. The Flop & Second Bet",
        "uthr-flow-3-desc": "The dealer reveals the first three community cards (the Flop). If you checked in the previous step, you now have two new choices:<br>• <b>Check:</b> Check again and wait for the remaining community cards.<br>• <b>Play Bet:</b> Make a bet of 2x your Ante bet in the 'Play' spot.",
        "uthr-flow-4-title": "4. The Turn & River & Final Bet",
        "uthr-flow-4-desc": "The dealer reveals the final two community cards. If you have checked twice, you now have only two choices:<br>• <b>Fold:</b> You forfeit the hand and lose both your Ante and Blind bets.<br>• <b>Play Bet:</b> Make a bet of 1x your Ante bet in the 'Play' spot.",
        "uthr-flow-5-title": "5. Showdown & Payouts",
        "uthr-flow-5-desc": "Both hands are revealed and the best five-card hand wins.<br>• <b>Dealer Qualification:</b> The dealer needs at least a pair to 'qualify'.<br>• <b>Blind Payout:</b> Pays only if your winning hand is a Straight or better (payout varies). If less than a Straight, the Blind pushes.<br>• <b>Ante Payout:</b> Pays 1-to-1 if you win and the dealer qualifies. If the dealer does not qualify, the Ante pushes.<br>• <b>Play Payout:</b> Pays 1-to-1 if you win.<br>• <b>Trips Payout:</b> Pays if your final hand is Three of a Kind or better, regardless of whether you beat the dealer.",

        // --- UTH Basic Strategy Page (uth-basic-strategy.html) ---
        "uths-title": "UTH Basic Strategy",
        "uths-intro": "The core strategy of UTH revolves around deciding 'when' and 'how much' to bet. The goal is to maximize your wager (3x or 4x) with strong hands, reserve options (Check) with developing hands, and cut your losses early (Fold) with weak hands.",
        "uths-preflop-title": "Pre-Flop Strategy: Raise 4x or Check",
        "uths-preflop-desc": "This is the most crucial decision of the hand, as it offers the chance to make your largest bet. A simple, effective strategy is to raise 4x with your strong, premium hands and check with all other hands. Checking isn't a sign of weakness; it's about gathering more information from the flop.",
        "uths-preflop-raise-title": "Recommended Hands to Raise 4x",
        "uths-pairs-title": "Pairs",
        "uths-pairs-desc": "3-3 and up",
        "uths-suited-title": "Suited",
        "uths-suited-desc": "Any Ace<br>K-5s and up<br>Q-8s and up<br>J-9s and up",
        "uths-offsuit-title": "Off-suit",
        "uths-offsuit-desc": "A-Jo and up<br>K-Qo",
        "uths-preflop-check": "* All other hands should Check.",
        "uths-flop-title": "Post-Flop Strategy: Raise 2x or Check",
        "uths-flop-desc": "If you checked pre-flop, after seeing the first three community cards, you must decide if your hand is strong enough to make a 2x bet.",
        "uths-flop-raise-title": "Situations to Raise 2x:",
        "uths-flop-cond1": "You have made Two Pair or better.",
        "uths-flop-cond2": "You have a 'hidden pair' (one of your hole cards pairs the board) that is a Top Pair or better. (e.g., You hold A-8 on an 8-5-K flop).",
        "uths-flop-cond3": "You have a four-card flush draw, and one of your hole cards is a 10 or higher.",
        "uths-flop-check": "* In other situations, you should Check.",
        "uths-river-title": "Turn/River Strategy: Raise 1x or Fold",
        "uths-river-desc": "If you've checked twice, this is your final decision after all five community cards are out. The rule is relatively simple:",
        "uths-river-raise-title": "Situations to Raise 1x:",
        "uths-river-cond1": "You have made a 'hidden pair' or better.",
        "uths-river-cond2": "A simple guideline: if your hand cannot beat a 'hidden pair' from the dealer (i.e., if the dealer pairs the lowest board card and you still lose), you should fold.",
        "uths-river-fold": "* All other hands should be folded without hesitation. Cut your losses.",
        "uths-trips-title": "A Note on the 'Trips' Bet",
        "uths-trips-desc": "The 'Trips' bet is an independent side bet that pays out if your final five-card hand is Three of a Kind or better. This bet has a relatively high house edge (around 3.5%) and is similar to a lottery ticket. Our main game strategy should not be influenced by this side bet."
    },
    zh: {
        // --- Global (Navigation & Footer) ---
        "nav-brand-text": "BUST THE CASINO",
        "nav-strategy": "策略中心",
        "nav-tools": "實戰工具",
        "nav-about": "關於我們",
        "footer-copyright": "&copy; 2025 Bust the Casino. 版權所有。",
        "footer-disclaimer": "請理智博弈，注意風險。本網站內容僅供學術探討和娛樂參考。",
        
        // --- Home Page (index.html) ---
        "hero-title-1": "掌控賭桌",
        "hero-title-2": "擊潰賭場",
        "hero-subtitle": "我們提供基於數學和數據的遊戲策略、教學和實戰工具，讓你成為更精明的玩家。",
        "hero-button": "探索遊戲策略",
        "strategy-title": "策略中心",
        "strategy-subtitle": "從最受歡迎的遊戲開始，掌握核心策略。",
        "blackjack-title": "21點",
        "blackjack-desc": "被公認為賭場中最能以技術取勝的遊戲。學習基本策略和算牌技巧，將莊家優勢降到最低。",
        "baccarat-title": "百家樂",
        "baccarat-desc": "節奏明快、規則簡單，深受亞洲玩家喜愛。了解莊、閒、和背後的數學，做出最有利的投注決策。",
        "uth-title": "Ultimate Texas Hold'em",
        "uth-desc": "結合德州撲克的技巧與賭場對戰的刺激感，學習根據你的底牌和公共牌，作出最佳的加注或棄牌決定。",

        // --- Blackjack Page (blackjack.html) ---
        "blackjack-page-title": "21點專區",
        "blackjack-page-subtitle": "掌握策略，將賭場優勢降至最低。從新手到進階，我們為你提供最全面的指南。",
        "blackjack-rules-title": "規則與玩法",
        "blackjack-rules-desc": "從零開始，學習21點的基本流程、牌值計算和各種遊戲選項。",
        "blackjack-basic-title": "基礎策略",
        "blackjack-basic-desc": "學習在任何情況下做出數學上的最佳決策，這是戰勝21點的第一步。",
        "blackjack-advanced-title": "進階技巧",
        "blackjack-advanced-desc": "探索算牌の世界，了解如何利用剩餘牌的組合來獲取真正優勢。",

        // --- Baccarat Page (baccarat.html) ---
        "baccarat-page-title": "百家樂專區",
        "baccarat-page-subtitle": "節奏明快，規則簡單。了解莊、閒、和背後的數學，做出最有利的投注決策。",
        "baccarat-rules-title": "規則與玩法",
        "baccarat-rules-desc": "從零開始，學習百家樂的派牌流程、補牌規則和不同下注選項。",
        "baccarat-basic-title": "基礎策略",
        "baccarat-basic-desc": "分析莊、閒、和的真實賠率與賭場優勢，了解為何押莊是數學上的最佳選擇。",
        "baccarat-divination-title": "概率啟示工具",
        "baccarat-divination-desc": "一個基於易經卦象的隨機模擬器，用來探索短期投注的概率波動性，僅供娛樂。",
        
        // --- UTH Page (uth.html) ---
        "uth-page-title": "Ultimate Texas Hold'em",
        "uth-page-subtitle": "結合了傳統德州撲克的刺激與賭場對戰的快感。學習何時下大注，是戰勝莊家的關鍵。",
        "uth-rules-title": "規則與玩法",
        "uth-rules-desc": "學習遊戲流程、不同階段的下注選項，以及最重要的德州撲克牌型大小。",
        "uth-basic-title": "基礎策略",
        "uth-basic-desc": "分析你的起手牌，學習在翻牌前、翻牌後何時應該下4倍、2倍或棄牌。",

        // --- Blackjack Rules Page (blackjack-rules.html) ---
        "back-to-blackjack": "&larr; 返回21點專區",
        "bkr-title": "規則與玩法",
        "bkr-obj-title": "遊戲目標",
        "bkr-obj-desc": "21點的目標非常簡單：在你的手牌點數總和不超過21點的情況下，盡可能地接近21點，並擊敗莊家的手牌。如果你一開始的兩張牌點數總和剛好是21點（一張A牌和一張10點牌），這就是 \"Blackjack\"，你會立即獲勝並獲得更高的賠率。",
        "bkr-card-title": "牌值計算",
        "bkr-card-1": "<b>數字牌 (2-10):</b> 牌值與其數字相同。",
        "bkr-card-2": "<b>公仔牌 (J, Q, K):</b> 每張牌值均為10點。",
        "bkr-card-3": "<b>A牌 (Ace):</b> 最特別的牌，牌值可以算作1點或11點，視乎哪種對玩家更有利。例如，(A, 8) 總和是19點。(A, 5, 8) 總和是14點 (A算作1點，否則會爆牌)。",
        "bkr-actions-title": "玩家的選擇",
        "bkr-hit-title": "要牌 (Hit):",
        "bkr-hit-desc": "要求莊家再給你一張牌。你可以持續要牌，直到你決定停牌或你的點數超過21點（爆牌）。",
        "bkr-stand-title": "停牌 (Stand):",
        "bkr-stand-desc": "對你目前的手牌感到滿意，不再要牌。輪到莊家行動。",
        "bkr-double-title": "加倍 (Double Down):",
        "bkr-double-desc": "在你拿到最初兩張牌後，你可以選擇將你的賭注加倍。但加倍後，你只能再拿一張牌，之後就必須停牌。這是一個在高勝率時增加盈利的關鍵策略。",
        "bkr-split-title": "分牌 (Split):",
        "bkr-split-desc": "如果你最初兩張牌的點數相同（例如兩張8或兩張K），你可以選擇分牌。你需要下一個與原賭注相等的注碼，然後這兩張牌會被分成兩手獨立的牌，你會為每一手牌單獨要牌或停牌。",
        "bkr-dealer-title": "莊家的規則",
        "bkr-dealer-desc": "莊家的行動沒有任何自由度，必須嚴格遵守賭場規則。通常規則是：莊家在總點數為16點或以下時必須要牌；在總點數為17點或以上時（包括軟17，即包含一張A牌的17點）必須停牌。",

        // --- Baccarat Rules Page (baccarat-rules.html) ---
        "back-to-baccarat": "&larr; 返回百家樂專區",
        "bcr-title": "規則與玩法",
        "bcr-obj-title": "遊戲目標",
        "bcr-obj-desc": "百家樂的目標比21點更簡單，你不是在跟莊家對決，而是在預測哪一方的手牌點數總和會更接近9點。你可以在「閒家」(Player)、「莊家」(Banker) 或「和局」(Tie) 三個區域下注。",
        "bcr-card-title": "牌值計算",
        "bcr-card-1": "<b>數字牌 (2-9):</b> 牌值與其數字相同。",
        "bcr-card-2": "<b>10, J, Q, K:</b> 每張牌值均為0點。",
        "bcr-card-3": "<b>A牌 (Ace):</b> 牌值為1點。",
        "bcr-card-desc": "手牌總點數只取個位數。例如，一手牌是7和8，總和是15，那麼這手牌的點數就是5。一手牌是K和9，總和是9，這就是最強的「例牌」。",
        "bcr-payouts-title": "下注與賠率",
        "bcr-player-title": "押閒家 (Player):",
        "bcr-player-desc": "如果你認為閒家的手牌會贏，賠率為1賠1。",
        "bcr-banker-title": "押莊家 (Banker):",
        "bcr-banker-desc": "如果你認為莊家的手牌會贏，賠率同樣為1賠1，但賭場會從你的贏利中抽取5%的佣金。這是因為莊家在數學上略有優勢。",
        "bcr-tie-title": "押和局 (Tie):",
        "bcr-tie-desc": "如果你認為雙方點數相同，賠率通常為1賠8。雖然賠率高，但這是莊家優勢最高的選項，不建議長期下注。",
        "bcr-third-title": "第三張牌規則",
        "bcr-third-desc": "這是百家樂最複雜的部分，但好消息是你不需要記住它，荷官會自動處理。規則決定了閒家和莊家在何時需要補第三張牌。",
        "bcr-third-player": "閒家規則:",
        "bcr-third-p1": "如果閒家最初兩張牌總點數為0-5，必須補牌。",
        "bcr-third-p2": "如果總點數為6-7，必須停牌。",
        "bcr-third-p3": "如果總點數為8-9 (例牌)，雙方都停牌，遊戲結束。",
        "bcr-third-banker": "莊家規則 (取決於閒家是否補牌以及補了什麼牌):",
        "bcr-third-b-desc": "莊家的規則更為複雜，總結如下表：",
        "bcr-table-b-total": "莊家首兩張總點",
        "bcr-table-p-card": "閒家補的第三張牌",
        "bcr-table-action": "莊家行動",
        "bcr-table-r1": "不是8",
        "bcr-table-hit1": "補牌",
        "bcr-table-r2": "是2, 3, 4, 5, 6, 7",
        "bcr-table-hit2": "補牌",
        "bcr-table-r3": "是4, 5, 6, 7",
        "bcr-table-hit3": "補牌",
        "bcr-table-r4": "是6, 7",
        "bcr-table-hit4": "補牌",
        "bcr-table-r5": "7",
        "bcr-table-stand": "停牌",

        // --- Blackjack Basic Strategy Page (blackjack-basic-strategy.html) ---
        "bks-title": "21點基礎策略",
        "bks-intro": "基礎策略是戰勝21點的基石。它基於數學概率，告訴你在任何情況下（你的手牌 vs 莊家明牌）應該做出哪個決定（要牌、停牌、加倍、分牌）才能最大化你的長期回報率。嚴格遵守此表，可以將莊家優勢降至約0.5%。",
        "bks-legend-title": "圖例",
        "bks-legend-h": "H = 要牌",
        "bks-legend-s": "S = 停牌",
        "bks-legend-d": "D = 加倍",
        "bks-legend-p": "P = 分牌",
        "bks-legend-sur": "SR = 投降",
        "bks-hard-title": "硬點 (Hard Totals)",
        "bks-soft-title": "軟點 (Soft Totals)",
        "bks-pairs-title": "對子 (Pairs)",
        "bks-dealer-card": "玩家手牌",
        "bks-dealer-card-2": "玩家手HSBCand",
        "bks-dealer-card-3": "玩家手牌",

        // --- Baccarat Basic Strategy Page (baccarat-basic-strategy.html) ---
        "bcs-title": "百家樂基礎策略",
        "bcs-intro": "百家樂的策略並非關於遊戲中的決策，而是關於下注前的選擇。與21點不同，一旦下注，遊戲過程就完全由規則決定。因此，唯一的策略就是選擇擁有最低莊家優勢的投注選項。",
        "bcs-analysis-title": "三大投注選項分析",
        "bcs-banker-title": "1. 押莊家 (Banker Bet) - 最佳選擇",
        "bcs-banker-desc": "儘管押莊贏錢後會被抽取5%的佣金，但它依然是數學上最有利的選擇。因為根據發牌規則，莊家手牌的贏率略高於閒家。",
        "bcs-banker-edge-label": "莊家優勢",
        "bcs-banker-win-label": "勝率",
        "bcs-player-title": "2. 押閒家 (Player Bet)",
        "bcs-player-desc": "押閒家的莊家優勢也非常低，是一個僅次於押莊的好選擇。如果你不想每次都計算佣金，押閒家也是一個可以接受的策略。",
        "bcs-player-edge-label": "莊家優勢",
        "bcs-player-win-label": "勝率",
        "bcs-tie-title": "3. 押和局 (Tie Bet) - 避免下注",
        "bcs-tie-desc": "雖然和局1賠8的賠率非常誘人，但其出現的機率極低，導致莊家優勢非常高。長期來看，押和局是虧損最快的投注方式。",
        "bcs-tie-edge-label": "莊家優勢",
        "bcs-tie-win-label": "出現機率",
        "bcs-summary-title": "結論：唯一嘅策略",
        "bcs-summary-desc": "百家樂嘅最佳策略非常簡單：**永遠都押莊家**。唔好被所謂嘅「路紙」或者直覺迷惑，數學證明咗押莊係你喺牌桌上可以做嘅最好決定。同時，**絕對要避免押和局**。",
        
        // --- Baccarat Divination Tool (baccarat-divination.html) ---
        "div-title": "概率啟示工具",
        "div-subtitle": "一個基於易經三爻卦的隨機數生成器",
        "placeholder": "點擊下方按鈕開始模擬",
        "btn-start": "開始模擬",
        "div-disclaimer": "免責聲-明：本工具純屬娛樂，其結果基於偽隨機算法，不代表任何真實世界的預測，亦不構成任何投注建議。請時刻以官方策略為準，理智博彩。",

        // --- Blackjack Advanced Strategy Page (blackjack-advanced-strategy.html) ---
        "bka-title": "進階技巧：算牌入門 (Hi-Lo System)",
        "bka-intro": "算牌並非電影中嘅超能力記憶，而係一套追蹤牌堆中大牌與細牌比例嘅系統。當牌堆中剩下嘅大牌（10, J, Q, K, A）比例較高時，對玩家極為有利，因為出現Blackjack嘅機率大增。Hi-Lo係最流行、最易上手嘅算牌系統。",
        "bka-step1-title": "第一步：賦予牌值 (Assigning Values)",
        "bka-step1-desc": "Hi-Lo系統將所有牌分為三類，並賦予簡單嘅數值。你嘅目標唔係記住每一張出過嘅牌，而係記住一個持續累加嘅數字。",
        "bka-step1-low": "低牌 (2, 3, 4, 5, 6)",
        "bka-step1-neutral": "中性牌 (7, 8, 9)",
        "bka-step1-high": "高牌 (10, J, Q, K, A)",
        "bka-step2-title": "第二步：計算流水數 (Running Count)",
        "bka-step2-desc": "從一副新牌（或一靴新牌）開始，流水數為0。每一張牌發出後，你根據上面嘅牌值喺腦中進行加減。",
        "bka-step2-example": "<b>例子:</b> 第一輪發出嘅牌係 10, 3, K, 8, A, 5。你嘅心算過程應該係：<br>10(-1), 3(+1), K(-1), 8(0), A(-1), 5(+1) → <span class='font-bold text-lg' style='color:var(--color-accent-gold);'>-1 + 1 - 1 + 0 - 1 + 1 = -1</span>。<br>所以，第一輪結束後，流水數係 <span class='font-bold'>-1</span>。你只需要記住呢個最終數字，然後喺下一輪繼續累加。",
        "bka-step2-goal": "一個正數嘅流水數 (e.g., +5) 代表目前為止出過嘅細牌比大牌多，牌堆對玩家有利。相反，一個負數則代表牌堆對莊家有利。",
        "bka-step3-title": "第三步：換算真數 (True Count) - 核心關鍵",
        "bka-step3-desc": "流水數本身有誤導性。喺剩餘6副牌時，+5嘅流水數意義不大；但如果只剩1副牌，+5就代表優勢極大。因此，我哋需要將流水數標準化，得出「真數」。",
        "bka-step3-formula": "真數 (True Count) = 流水數 (Running Count) / 剩餘牌副數 (Decks Remaining)",
        "bka-step3-example": "<b>例子:</b> 你嘅流水數係+10，而賭桌上用嘅係6副牌，你估計大約仲剩4副牌未發。咁你嘅真數就係：<br><span class='font-bold text-lg' style='color:var(--color-accent-gold);'>+10 / 4 = +2.5</span>。真數先至係你調整注碼嘅真正依據。估算剩餘牌副數需要大量練習。",
        "bka-step4-title": "第四步：調整注碼 (Bet Spreading)",
        "bka-step4-desc": "算牌嘅最終目的就係喺你擁有優勢嘅時候下大注，冇優勢嘅時候下細注或離場。你應該預先設定好你嘅投注單位同策略。",
        "bka-table-tc": "真數 (True Count)",
        "bka-table-bet": "建議注碼 (Bet)",
        "bka-table-advantage": "玩家優勢 (Player Edge)",
        "bka-bet1": "1 個單位 (最低注)",
        "bka-bet2": "2 個單位",
        "bka-bet3": "4 個單位",
        "bka-bet4": "8 個單位",
        "bka-bet5": "10-12 個單位",
        "bka-disclaimer-title": "重要警告",
        "bka-disclaimer-desc": "算牌極具挑戰性，需要大量練習才能在嘈雜嘅賭場環境中保持準確。同時，賭場會主動尋找並驅逐算牌客。本教學僅供學術研究，切勿輕易嘗試，風險自負。",
        
        // --- UTH Rules Page (uth-rules.html) ---
        "back-to-uth": "&larr; 返回UTH專區",
        "uthr-title": "UTH 規則與玩法",
        "uthr-obj-title": "遊戲目標",
        "uthr-obj-desc": "Ultimate Texas Hold'em 嘅目標係用你手上嘅兩張底牌同五張公共牌，組合出最大嘅五張牌型，並擊敗莊家。與傳統德州撲克唔同，你係同莊家對決，而唔係其他玩家。",
        "uthr-hands-title": "撲克牌型大小",
        "uthr-hands-desc": "牌型大小同傳統德州撲克完全一樣，由大到細排列如下：",
        "uthr-table-rank": "排名",
        "uthr-table-hand": "牌型",
        "uthr-table-example": "例子",
        "uthr-rank-1": "皇家同花順",
        "uthr-rank-2": "同花順",
        "uthr-rank-3": "四條 (鐵支)",
        "uthr-rank-4": "葫蘆 (滿堂彩)",
        "uthr-rank-5": "同花 (花)",
        "uthr-rank-6": "順子",
        "uthr-rank-7": "三條",
        "uthr-rank-8": "兩對",
        "uthr-rank-9": "一對",
        "uthr-rank-10": "高牌 (散牌)",
        "uthr-flow-title": "遊戲流程與下注",
        "uthr-flow-1-title": "1. 開始下注 (Ante & Blind)",
        "uthr-flow-1-desc": "遊戲開始前，你必須下兩個等額嘅注碼：「盲注 (Blind)」同「底注 (Ante)」。例如，你喺盲注區下$10，就必須喺底注區下$10。你亦可以選擇性喺「旅程 (Trips)」獎賞區下注。",
        "uthr-flow-2-title": "2. 派牌 & 第一次下注 (Pre-Flop)",
        "uthr-flow-2-desc": "你同莊家會各自收到兩張底牌（面朝下）。睇完你嘅底牌後，你有兩個選擇：<br>• <b>過牌 (Check):</b> 唔做任何事，等待睇公共牌。<br>• <b>加注 (Play Bet):</b> 喺「遊戲注 (Play)」區下一個等於你底注3倍或4倍嘅注碼。一旦加注，呢一局你就唔可以再加注。",
        "uthr-flow-3-title": "3. 翻牌 & 第二次下注 (The Flop)",
        "uthr-flow-3-desc": "莊家會發出三張公共牌（面朝上）。如果你喺上一步選擇咗過牌，而家你有兩個新選擇：<br>• <b>過牌 (Check):</b> 再次過牌，等待睇之後嘅公共牌。<br>• <b>加注 (Play Bet):</b> 喺「遊戲注」區下一個等於你底注2倍嘅注碼。",
        "uthr-flow-4-title": "4. 轉牌與河牌 & 最後下注 (Turn & River)",
        "uthr-flow-4-desc": "莊家會發出最後兩張公共牌。如果你之前兩次都選擇過牌，而家你只剩下兩個選擇：<br>• <b>棄牌 (Fold):</b> 你放棄呢一局，輸掉你嘅盲注同底注。<br>• <b>加注 (Play Bet):</b> 喺「遊戲注」區下一個等於你底注1倍嘅注碼。",
        "uthr-flow-5-title": "5. 開牌比大小 (Showdown) & 派彩",
        "uthr-flow-5-desc": "雙方開牌，用各自嘅兩張底牌同五張公共牌組成最大嘅五張牌型比大小。<br>• <b>莊家「夠格」(Qualify):</b> 莊家至少要有一對或以上嘅牌型先算「夠格」。<br>• <b>盲注派彩:</b> 只有喺你贏咗，並且你嘅牌型係順子或以上時先會派彩（賠率視乎牌型大小）。如果牌型細過順子，盲注會退還 (Push)。<br>• <b>底注派彩:</b> 只有喺你贏咗，並且莊家夠格嘅情況下先會派彩 (1賠1)。如果莊家唔夠格，底注會退還。<br>• <b>遊戲注派彩:</b> 只要你贏咗就會派彩 (1賠1)。<br>• <b>旅程注派彩:</b> 只要你嘅最終牌型係三條或以上，不論輸贏都會根據賠率表派彩。",
        
        // --- UTH Basic Strategy Page (uth-basic-strategy.html) ---
        "uths-title": "UTH 基礎策略",
        "uths-intro": "UTH嘅核心策略就係決定「何時」以及「下注多少」。目標係喺有好牌時最大化你嘅注碼 (3倍或4倍)，喺牌唔明朗時保留選擇權 (過牌)，並喺劣勢時盡早放棄 (棄牌)。",
        "uths-preflop-title": "翻牌前策略 (Pre-Flop): 4倍加注或過牌",
        "uths-preflop-desc": "呢個係成局遊戲中最重要嘅決定，因為佢俾你機會落最大嘅注碼。一個簡單有效嘅策略係，只用你嘅強牌去加注4倍，其他所有牌都選擇過牌。過牌並唔代表你弱，只係代表你想睇埋頭三張公共牌再決定。",
        "uths-preflop-raise-title": "建議加注4倍 (Raise 4x) 的起手牌",
        "uths-pairs-title": "對子 (Pairs)",
        "uths-pairs-desc": "3-3 或以上",
        "uths-suited-title": "同花 (Suited)",
        "uths-suited-desc": "任何 A<br>K-5s 或以上<br>Q-8s 或以上<br>J-9s 或以上",
        "uths-offsuit-title": "非同花 (Off-suit)",
        "uths-offsuit-desc": "A-Jo 或以上<br>K-Qo",
        "uths-preflop-check": "* 所有其他牌都應該選擇過牌 (Check)。",
        "uths-flop-title": "翻牌後策略 (The Flop): 2倍加注或過牌",
        "uths-flop-desc": "如果你喺翻牌前選擇過牌，睇完頭三張公共牌後，你需要決定係咪值得落一個2倍嘅注碼。",
        "uths-flop-raise-title": "建議加注2倍 (Raise 2x) 的情況：",
        "uths-flop-cond1": "你組成咗「兩對」或更好嘅牌型。",
        "uths-flop-cond2": "你手上嘅其中一張底牌同公共牌組成咗一對 (稱為隱藏對子, Hidden Pair)，並且呢對牌係頂對 (Top Pair) 或更好。 (例如：你手持 A-8，公共牌係 8-5-K)",
        "uths-flop-cond3": "你差一張就組成同花 (即有四張同花牌)，並且你嘅其中一張底牌係 10 或以上。",
        "uths-flop-check": "* 其他情況都應該選擇過牌 (Check)。",
        "uths-river-title": "轉牌/河牌後策略 (Turn/River): 1倍加注或棄牌",
        "uths-river-desc": "如果你過牌兩次，睇晒五張公共牌之後，呢個係你最後嘅決定。規則相對簡單：",
        "uths-river-raise-title": "建議加注1倍 (Raise 1x) 的情況：",
        "uths-river-cond1": "你組成咗「隱藏對子」(Hidden Pair) 或更好嘅牌型。",
        "uths-river-cond2": "一個簡單嘅判斷標準：如果你嘅牌細過莊家嘅「隱藏對子」(即係話，如果莊家對中公共牌嘅最細一張牌，而你都贏唔到)，就應該棄牌。",
        "uths-river-fold": "* 其他所有牌都應該果斷棄牌 (Fold)，輸少當贏。",
        "uths-trips-title": "關於「旅程 (Trips)」注",
        "uths-trips-desc": "「旅程」注係一個獨立嘅邊注，佢只係賭你最終嘅五張牌能否組成三條或以上嘅牌型。呢個注嘅莊家優勢相對較高 (約3.5%)，類似買彩票。我哋嘅主要策略唔應該受到呢個邊注嘅影響。"
    }
};
