const languages = {
    en: {
        // --- Global (Navigation & Footer) ---
        "nav-brand": "BUST THE CASINO",
        "nav-games": "Games",
        "nav-strategy": "Strategy",
        "nav-tools": "Tools",
        "nav-about": "About Us",
        "footer-copyright": "&copy; 2025 Bust the Casino. All Rights Reserved.",
        "footer-disclaimer": "Please gamble responsibly. This website is for academic and entertainment purposes only.",

        // --- Home Page (index.html) ---
        "hero-title-1": "STOP RELYING ON LUCK",
        "hero-title-2": "BEAT THE CASINO WITH STRATEGY",
        "hero-subtitle": "We provide data-driven game strategies, tutorials, and practical tools to make you a smarter player.",
        "hero-button": "Explore Game Strategies",
        "games-title": "CHOOSE YOUR GAME",
        "games-subtitle": "Start with the most popular games to master the core strategies.",
        "blackjack-title": "Blackjack",
        "blackjack-desc": "Known as the most skill-based game in the casino. Learn basic strategy and card counting to minimize the house edge.",
        "baccarat-title": "Baccarat",
        "baccarat-desc": "A fast-paced and simple game beloved by many players. Understand the math behind Player, Banker, and Tie bets to make the most informed decisions.",

        // --- Blackjack Page (blackjack.html) ---
        "blackjack-page-title": "Blackjack Section",
        "blackjack-page-subtitle": "Master the strategy to minimize the house edge. We provide a comprehensive guide from beginner to advanced.",
        "blackjack-rules-title": "Rules & How to Play",
        "blackjack-rules-desc": "Start from scratch and learn the basic flow, card values, and various options in Blackjack.",
        "blackjack-basic-title": "Basic Strategy",
        "blackjack-basic-desc": "Learn to make the mathematically optimal decision in any situation. This is the first step to beating Blackjack.",
        "blackjack-advanced-title": "Advanced Strategy",
        "blackjack-advanced-desc": "Explore the world of card counting and learn how to gain a real advantage over the house.",

        // --- Baccarat Page (baccarat.html) ---
        "baccarat-page-title": "Baccarat Section",
        "baccarat-page-subtitle": "Fast-paced and simple rules. Understand the math behind Player, Banker, and Tie to make the best betting decisions.",
        "baccarat-rules-title": "Rules & How to Play",
        "baccarat-rules-desc": "Start from scratch and learn the dealing process, third-card rules, and different betting options.",
        "baccarat-basic-title": "Basic Strategy",
        "baccarat-basic-desc": "Analyze the true odds and house edge of each bet to understand why betting on the Banker is the best mathematical choice.",
        "baccarat-advanced-title": "Advanced Strategy",
        "baccarat-advanced-desc": "Debunk the myths of 'The Road', explore the traps of side bets, and learn robust bankroll management.",

        // --- Blackjack Rules Page (blackjack-rules.html) ---
        "back-to-blackjack": "&larr; Back to Blackjack Section",
        "bkr-title": "Rules & How to Play",
        "bkr-obj-title": "Objective of the Game",
        "bkr-obj-desc": "The objective of Blackjack is simple: get a hand total closer to 21 than the dealer, without going over 21. If your first two cards total exactly 21 (an Ace and a 10-value card), you have a \"Blackjack\" and win immediately with a higher payout.",
        "bkr-card-title": "Card Values",
        "bkr-card-1": "<b>Number Cards (2-10):</b> Are worth their face value.",
        "bkr-card-2": "<b>Face Cards (J, Q, K):</b> Are each worth 10 points.",
        "bkr-card-3": "<b>Ace (A):</b> Is the most special card. It can be worth 1 or 11, whichever is more favorable for the hand. For example, (A, 8) is 19. (A, 5, 8) is 14 (the Ace counts as 1 to avoid busting).",
        "bkr-actions-title": "Player's Actions",
        "bkr-hit-title": "Hit:",
        "bkr-hit-desc": "Request another card from the dealer. You can keep hitting until you decide to stand or your total exceeds 21 (bust).",
        "bkr-stand-title": "Stand:",
        "bkr-stand-desc": "You are satisfied with your hand and want to take no more cards. It is then the dealer's turn to act.",
        "bkr-double-title": "Double Down:",
        "bkr-double-desc": "After receiving your first two cards, you can choose to double your initial bet. In return, you receive only one more card and must stand afterward. This is a key strategy to increase profit in favorable situations.",
        "bkr-split-title": "Split:",
        "bkr-split-desc": "If your first two cards are of the same value (e.g., two 8s or two Kings), you can split them into two separate hands. You must place an additional bet equal to your original bet. You then play each hand independently.",
        "bkr-dealer-title": "Dealer's Rules",
        "bkr-dealer-desc": "The dealer has no freedom of choice and must follow strict house rules. Typically, the dealer must hit on a total of 16 or less and must stand on a total of 17 or more (including a soft 17, which is an Ace and a 6).",

        // --- Baccarat Rules Page (baccarat-rules.html) ---
        "back-to-baccarat": "&larr; Back to Baccarat Section",
        "bcr-title": "Rules & How to Play",
        "bcr-obj-title": "Objective of the Game",
        "bcr-obj-desc": "The goal in Baccarat is simpler than Blackjack. You are not playing against the dealer; instead, you are betting on which of two hands, the \"Player\" or the \"Banker\", will have a total closest to 9.",
        "bcr-card-title": "Card Values",
        "bcr-card-1": "<b>Number Cards (2-9):</b> Are worth their face value.",
        "bcr-card-2": "<b>10, J, Q, K:</b> Are each worth 0 points.",
        "bcr-card-3": "<b>Ace (A):</b> Is worth 1 point.",
        "bcr-card-desc": "The total value of a hand is the rightmost digit of the sum of the cards. For example, a hand of 7 and 8 totals 15, so its value is 5. A hand of K and 9 has a value of 9, which is a \"Natural\".",
        "bcr-payouts-title": "Bets and Payouts",
        "bcr-player-title": "Bet on Player:",
        "bcr-player-desc": "If you bet on the Player hand to win, the payout is 1 to 1.",
        "bcr-banker-title": "Bet on Banker:",
        "bcr-banker-desc": "If you bet on the Banker hand to win, the payout is also 1 to 1, but the house takes a 5% commission from the winnings. This is because the Banker bet has a slightly higher mathematical probability of winning.",
        "bcr-tie-title": "Bet on Tie:",
        "bcr-tie-desc": "If you bet that both hands will have the same total, the payout is typically 8 to 1. While the payout is high, this is the worst bet in terms of house edge and is not recommended for long-term play.",
        "bcr-third-title": "The Third Card Rule",
        "bcr-third-desc": "This is the most complicated part of Baccarat, but the good news is you don't need to memorize it; the dealer handles it automatically. The rules dictate when the Player and Banker must draw a third card.",
        "bcr-third-player": "Player's Rule:",
        "bcr-third-p1": "If the Player's first two cards total 0-5, the Player must draw a third card.",
        "bcr-third-p2": "If the total is 6 or 7, the Player must stand.",
        "bcr-third-p3": "If the total is 8 or 9 (a \"Natural\"), both hands stand and the game ends.",
        "bcr-third-banker": "Banker's Rule (depends on the Player's third card):",
        "bcr-third-b-desc": "The Banker's rule is more complex, as summarized in the table below:",
        "bcr-table-b-total": "Banker's First Two-Card Total",
        "bcr-table-p-card": "Player's Third Card",
        "bcr-table-action": "Banker's Action",
        "bcr-table-r1": "is not 8",
        "bcr-table-hit1": "Draw",
        "bcr-table-r2": "is 2, 3, 4, 5, 6, 7",
        "bcr-table-hit2": "Draw",
        "bcr-table-r3": "is 4, 5, 6, 7",
        "bcr-table-hit3": "Draw",
        "bcr-table-r4": "is 6, 7",
        "bcr-table-hit4": "Draw",
        "bcr-table-r5": "7",
        "bcr-table-stand": "Stand"
    },
    zh: {
        // --- Global (Navigation & Footer) ---
        "nav-brand": "BUST THE CASINO",
        "nav-games": "遊戲專區",
        "nav-strategy": "策略中心",
        "nav-tools": "實戰工具",
        "nav-about": "關於我們",
        "footer-copyright": "&copy; 2025 Bust the Casino. 版權所有。",
        "footer-disclaimer": "請理智博弈，注意風險。本網站內容僅供學術探討和娛樂參考。",
        
        // --- Home Page (index.html) ---
        "hero-title-1": "唔再靠運氣",
        "hero-title-2": "用策略戰勝賭場",
        "hero-subtitle": "我們提供基於數學和數據的遊戲策略、教學和實戰工具，讓你成為更精明的玩家。",
        "hero-button": "探索遊戲策略",
        "games-title": "選擇你的遊戲",
        "games-subtitle": "從最受歡迎的遊戲開始，掌握核心策略。",
        "blackjack-title": "21點",
        "blackjack-desc": "被公認為賭場中最能以技術取勝的遊戲。學習基本策略和算牌技巧，將莊家優勢降到最低。",
        "baccarat-title": "百家樂",
        "baccarat-desc": "節奏明快、規則簡單，深受亞洲玩家喜愛。了解莊、閒、和背後的數學，做出最有利的投注決策。",

        // --- Blackjack Page (blackjack.html) ---
        "blackjack-page-title": "21點專區",
        "blackjack-page-subtitle": "掌握策略，將賭場優勢降至最低。從新手到進階，我們為你提供最全面的指南。",
        "blackjack-rules-title": "規則與玩法",
        "blackjack-rules-desc": "從零開始，學習21點的基本流程、牌值計算和各種遊戲選項。",
        "blackjack-basic-title": "基礎策略",
        "blackjack-basic-desc": "學習在任何情況下做出數學上的最佳決策，這是戰勝21點的第一步。",
        "blackjack-advanced-title": "進階技巧",
        "blackjack-advanced-desc": "探索算牌的世界，了解如何利用剩餘牌的組合來獲取真正優勢。",

        // --- Baccarat Page (baccarat.html) ---
        "baccarat-page-title": "百家樂專區",
        "baccarat-page-subtitle": "節奏明快，規則簡單。了解莊、閒、和背後的數學，做出最有利的投注決策。",
        "baccarat-rules-title": "規則與玩法",
        "baccarat-rules-desc": "從零開始，學習百家樂的派牌流程、補牌規則和不同下注選項。",
        "baccarat-basic-title": "基礎策略",
        "baccarat-basic-desc": "分析莊、閒、和的真實賠率與賭場優勢，了解為何押莊是數學上的最佳選擇。",
        "baccarat-advanced-title": "進階技巧",
        "baccarat-advanced-desc": "破解路紙迷思，探討邊注的陷阱，並學習穩健的資金管理策略。",
        
        // --- Blackjack Rules Page (blackjack-rules.html) ---
        "back-to-blackjack": "&larr; 返回21點專區",
        "bkr-title": "規則與玩法",
        "bkr-obj-title": "遊戲目標",
        "bkr-obj-desc": "21點的目標非常簡單：在你的手牌點數總和不超過21點的情況下，盡可能地接近21點，並擊敗莊家的手牌。如果你一開始的兩張牌點數總和剛好是21點（一張A牌和一張10點牌），這就是 \"Blackjack\"，你會立即獲勝並獲得更高的賠率。",
        "bkr-card-title": "牌值計算",
        "bkr-card-1": "<b>數字牌 (2-10):</b> 牌值與其數字相同。",
        "bkr-card-2": "<b>公仔牌 (J, Q, K):</b> 每張牌值均為10點。",
        "bkr-card-3": "<b>A牌 (Ace):</b> 最特別的牌，牌值可以算作1點或11點，視乎哪種對玩家更有利。例如，(A, 8) 總和是19點。(A, 5, 8) 總和是14點 (A算作1點，否則會爆牌)。",
        "bkr-actions-title": "玩家的選擇",
        "bkr-hit-title": "要牌 (Hit):",
        "bkr-hit-desc": "要求莊家再給你一張牌。你可以持續要牌，直到你決定停牌或你的點數超過21點（爆牌）。",
        "bkr-stand-title": "停牌 (Stand):",
        "bkr-stand-desc": "對你目前的手牌感到滿意，不再要牌。輪到莊家行動。",
        "bkr-double-title": "加倍 (Double Down):",
        "bkr-double-desc": "在你拿到最初兩張牌後，你可以選擇將你的賭注加倍。但加倍後，你只能再拿一張牌，之後就必須停牌。這是一個在高勝率時增加盈利的關鍵策略。",
        "bkr-split-title": "分牌 (Split):",
        "bkr-split-desc": "如果你最初兩張牌的點數相同（例如兩張8或兩張K），你可以選擇分牌。你需要下一個與原賭注相等的注碼，然後這兩張牌會被分成兩手獨立的牌，你會為每一手牌單獨要牌或停牌。",
        "bkr-dealer-title": "莊家的規則",
        "bkr-dealer-desc": "莊家的行動沒有任何自由度，必須嚴格遵守賭場規則。通常規則是：莊家在總點數為16點或以下時必須要牌；在總點數為17點或以上時（包括軟17，即包含一張A牌的17點）必須停牌。",

        // --- Baccarat Rules Page (baccarat-rules.html) ---
        "back-to-baccarat": "&larr; 返回百家樂專區",
        "bcr-title": "規則與玩法",
        "bcr-obj-title": "遊戲目標",
        "bcr-obj-desc": "百家樂的目標比21點更簡單，你不是在跟莊家對決，而是在預測哪一方的手牌點數總和會更接近9點。你可以在「閒家」(Player)、「莊家」(Banker) 或「和局」(Tie) 三個區域下注。",
        "bcr-card-title": "牌值計算",
        "bcr-card-1": "<b>數字牌 (2-9):</b> 牌值與其數字相同。",
        "bcr-card-2": "<b>10, J, Q, K:</b> 每張牌值均為0點。",
        "bcr-card-3": "<b>A牌 (Ace):</b> 牌值為1點。",
        "bcr-card-desc": "手牌總點數只取個位數。例如，一手牌是7和8，總和是15，那麼這手牌的點數就是5。一手牌是K和9，總和是9，這就是最強的「例牌」。",
        "bcr-payouts-title": "下注與賠率",
        "bcr-player-title": "押閒家 (Player):",
        "bcr-player-desc": "如果你認為閒家的手牌會贏，賠率為1賠1。",
        "bcr-banker-title": "押莊家 (Banker):",
        "bcr-banker-desc": "如果你認為莊家的手牌會贏，賠率同樣為1賠1，但賭場會從你的贏利中抽取5%的佣金。這是因為莊家在數學上略有優勢。",
        "bcr-tie-title": "押和局 (Tie):",
        "bcr-tie-desc": "如果你認為雙方點數相同，賠率通常為1賠8。雖然賠率高，但這是莊家優勢最高的選項，不建議長期下注。",
        "bcr-third-title": "第三張牌規則",
        "bcr-third-desc": "這是百家樂最複雜的部分，但好消息是你不需要記住它，荷官會自動處理。規則決定了閒家和莊家在何時需要補第三張牌。",
        "bcr-third-player": "閒家規則:",
        "bcr-third-p1": "如果閒家最初兩張牌總點數為0-5，必須補牌。",
        "bcr-third-p2": "如果總點數為6-7，必須停牌。",
        "bcr-third-p3": "如果總點數為8-9 (例牌)，雙方都停牌，遊戲結束。",
        "bcr-third-banker": "莊家規則 (取決於閒家是否補牌以及補了什麼牌):",
        "bcr-third-b-desc": "莊家的規則更為複雜，總結如下表：",
        "bcr-table-b-total": "莊家首兩張總點",
        "bcr-table-p-card": "閒家補的第三張牌",
        "bcr-table-action": "莊家行動",
        "bcr-table-r1": "不是8",
        "bcr-table-hit1": "補牌",
        "bcr-table-r2": "是2, 3, 4, 5, 6, 7",
        "bcr-table-hit2": "補牌",
        "bcr-table-r3": "是4, 5, 6, 7",
        "bcr-table-hit3": "補牌",
        "bcr-table-r4": "是6, 7",
        "bcr-table-hit4": "補牌",
        "bcr-table-r5": "7",
        "bcr-table-stand": "停牌"
    }
};

